
-- This query extracts the table for the pressor model study
-- The following views required to run this query:
--  1) norepinephrine_dose - generated by ../durations/norepinephrine-dose.sql
--  2) epinephrine_dose - generated by ../durations/epinephrine-dose.sql
--  3) dopamine_dose - generated by ../durations/dopamine-dose.sql
--  4) dobutamine_dose - generated by ../durations/dobutamine-dose.sql

DROP MATERIALIZED VIEW IF EXISTS pressor_model;
CREATE MATERIALIZED VIEW pressor_model as



with co_stg as
(
  select icustay_id, hadm_id
  , date_trunc('hour', intime) as intime
  , outtime
  , generate_series
  (
    -1,
    ceil(extract(EPOCH from outtime-intime)/60.0/60.0)::INTEGER
  )
, co as
(
  select icustay_id, hadm_id, intime, outtime
  , hr*(interval '1' hour) + intime - interval '1' hour as starttime
  , hr*(interval '1' hour) + intime as endtime
  , hr
  from co_stg
)





select
      co.icustay_id
    , epi.vaso_rate as rate_epinephrine
    , nor.vaso_rate as rate_norepinephrine
    , dop.vaso_rate as rate_dopamine
    , dob.vaso_rate as rate_dobutamine
  left join epinephrine_dose epi
    on co.icustay_id = epi.icustay_id
    and co.endtime > epi.starttime
    and co.endtime <= epi.endtime
  left join norepinephrine_dose nor
    on co.icustay_id = nor.icustay_id
    and co.endtime > nor.starttime
    and co.endtime <= nor.endtime
  left join dopamine_dose dop
    on co.icustay_id = dop.icustay_id
    and co.endtime > dop.starttime
    and co.endtime <= dop.endtime
  left join dobutamine_dose dob
    on co.icustay_id = dob.icustay_id
    and co.endtime > dob.starttime
    and co.endtime <= dob.endtime
)

